basedir = "/Users/kon8116/projects/kroger"

##################################################
# msl-checkout
##################################################

[[repos.msl-checkout.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-checkout.git"

[[repos.msl-checkout.branch]]
name = "master"
interval = "1h"
remotes = ["origin"]

#####
# msl-profile
#####

[[repos.msl-profile.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-profile.git"

[[repos.msl-profile.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# msl-wellness
#####

[[repos.msl-wellness.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-wellness.git"

[[repos.msl-wellness.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# message-center
#####

[[repos.message-center.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/message-center.git"

[[repos.message-center.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# msl-bootstrap
#####

[[repos.msl-bootstrap.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-bootstrap.git"

[[repos.msl-bootstrap.branch]]
name = "dev"
interval = "15m"
remotes = ["origin"]

#####
# msl-product-catalog
#####

[[repos.msl-product-catalog.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-product-catalog.git"

[[repos.msl-product-catalog.branch]]
name = "dev"
interval = "15m"
remotes = ["origin"]

#####
# communications-preferences
#####

[[repos.communications-preferences.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/communications-preferences.git"

[[repos.communications-preferences.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# optup-receipt-kafka-consumer
#####

[[repos.optup-receipt-kafka-consumer.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/optup-receipt-kafka-consumer.git"

[[repos.optup-receipt-kafka-consumer.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# optup-receipt-test-data-producer
#####

[[repos.optup-receipt-test-data-producer.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/optup-receipt-test-data-producer.git"

[[repos.optup-receipt-test-data-producer.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# msl-rx
#####

[[repos.msl-rx.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-rx.git"

[[repos.msl-rx.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# msl-coupons
#####

[[repos.msl-coupons.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-coupons.git"

[[repos.msl-coupons.branch]]
name = "dev"
interval = "15m"
remotes = ["origin"]

#####
# msl-rewards
#####

[[repos.msl-rewards.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-rewards.git"

[[repos.msl-rewards.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# comm-optin
#####

[[repos.comm-optin.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/comm-optin.git"

[[repos.comm-optin.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# msl-communications
#####

[[repos.msl-communications.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-communications.git"

[[repos.msl-communications.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# msl-usage-analytics
#####

[[repos.msl-usage-analytics.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-usage-analytics.git"

[[repos.msl-usage-analytics.branch]]
name = "dev"
interval = "15m"
remotes = ["origin"]

#####
# msl-order-history
#####

[[repos.msl-order-history.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-order-history.git"

[[repos.msl-order-history.branch]]
name = "dev"
interval = "15m"
remotes = ["origin"]

#####
# postmaster-listener
#####

[[repos.postmaster-listener.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/postmaster-listener.git"

[[repos.postmaster-listener.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# voice-assistant-poc
#####

[[repos.voice-assistant-poc.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/voice-assistant-poc.git"

[[repos.voice-assistant-poc.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# msl-weekly-ads
#####

[[repos.msl-weekly-ads.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-weekly-ads.git"

[[repos.msl-weekly-ads.branch]]
name = "dev"
interval = "15m"
remotes = ["origin"]

#####
# msl-store-locator
#####

[[repos.msl-store-locator.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-store-locator.git"

[[repos.msl-store-locator.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# msl-passbook
#####

[[repos.msl-passbook.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-passbook.git"

[[repos.msl-passbook.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# msl-cart
#####

[[repos.msl-cart.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-cart.git"

[[repos.msl-cart.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# msl-giftcards
#####

[[repos.msl-giftcards.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-giftcards.git"

[[repos.msl-giftcards.branch]]
name = "dev"
interval = "15m"
remotes = ["origin"]

#####
# msl-fulfillment
#####

[[repos.msl-fulfillment.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-fulfillment.git"

[[repos.msl-fulfillment.branch]]
name = "dev"
interval = "15m"
remotes = ["origin"]

#####
# msl-community-rewards
#####

[[repos.msl-community-rewards.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-community-rewards.git"

[[repos.msl-community-rewards.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# msl-shopping-list
#####

[[repos.msl-shopping-list.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-shopping-list.git"

[[repos.msl-shopping-list.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# msl-aisle-feedback
#####

[[repos.msl-aisle-feedback.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/msl-aisle-feedback.git"

[[repos.msl-aisle-feedback.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# mobile-content-api
#####

[[repos.mobile-content-api.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/mobile-content-api.git"

[[repos.mobile-content-api.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

##########
# Utilities
##########
#####
# utilities/msl-common-lib
#####

[[repos.'utilities/msl-common-lib'.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/utilities/msl-common-lib.git"

[[repos.'utilities/msl-common-lib'.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# utilities/msl-examples
#####

[[repos.'utilities/msl-examples'.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/utilities/msl-examples.git"

[[repos.'utilities/msl-examples'.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# utilities/msl-e2e-customer-journey-tests
#####

[[repos.'utilities/msl-e2e-customer-journey-tests'.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/utilities/msl-e2e-customer-journey-tests.git"

[[repos.'utilities/msl-e2e-customer-journey-tests'.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# utilities/msl-project-template
#####

[[repos.'utilities/msl-project-template'.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/utilities/msl-project-template.git"

[[repos.'utilities/msl-project-template'.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# utilities/msl-gradle-plugins
#####

[[repos.'utilities/msl-gradle-plugins'.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/utilities/msl-gradle-plugins.git"

[[repos.'utilities/msl-gradle-plugins'.branch]]
name = "master"
interval = "15m"
remotes = ["origin"]

#####
# utilities/admin-passbook-certs
#####

[[repos.'utilities/admin-passbook-certs'.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/utilities/admin-passbook-certs.git"

[[repos.'utilities/admin-passbook-certs'.branch]]
name = "dev"
interval = "15m"
remotes = ["origin"]

#####
# utilities/msl-ecsb-config-template
#####

[[repos.'utilities/msl-ecsb-config-template'.remotes]]
name = "origin"
url = "git@gitlab.kroger.com:msl/utilities/msl-ecsb-config-template.git"

[[repos.'utilities/msl-ecsb-config-template'.branch]]
name = "dev"
interval = "15m"
remotes = ["origin"]
