basedir = "/home/jozias/projects/rust-lang"

[[repos.ar2.remotes]]
name = "origin"
url = "jozias@jasonozias.com:repos/ar2.git"

[[repos.ar2.branch]]
name = "master"
interval = "1m"
remotes = ["origin"]

[[repos.node.remotes]]
name = "origin"
url = "git@github.com:nodejs/node.git"

[[repos.node.branch]]
name = "master"
interval = "1m"
remotes = ["origin"]

[[repos.repomons.remotes]]
name = "origin"
url = "jozias@jasonozias.com:repos/repomon.git"

[[repos.repomons.remotes]]
name = "gh"
url = "git@github.com:rustyhorde/repomon.git"

[[repos.repomons.remotes]]
name = "bb"
url = "git@bitbucket.org:rustyhorde/repomon.git"

[[repos.repomons.remotes]]
name = "gl"
url = "git@gitlab.com:rustyhorde/repomon.git"

[[repos.repomons.branch]]
name = "master"
interval = "30s"
remotes = ["origin", "gh", "bb"]
